version: 3

tasks:
  update:
    cmds:
      - nix flake update
      - nix flake archive

  home:
    cmds:
      - task: add-files
      - home-manager switch --flake .

  host:
    cmds:
      - task: add-files
      - sudo nixos-rebuild switch --flake .

  add-files:
    silent: true
    cmds:
      - |
        cd files
        for file in *;
        do
          nix store add-file $file
        done
