version: 3

tasks:
  fmt:
    cmds:
      - nixfmt .

  update:
    cmds:
      - nix flake update
      - task: archive

  archive:
    cmds:
      - nix flake archive

  home:
    cmds:
      - task: add-files
      - nh home switch . -- --impure

  host:
    cmds:
      - task: add-files
      - nh os switch --flake .

  add-files:
    silent: true
    ignore_error: true
    cmds:
      - |
        cd files
        for file in *;
        do
          nix store add-file $file
        done
