{ ... }:
{
  "Q" = "quitall";
  "q" = "quit";
  "R" = "reload_cwd";
  "F" = "set freeze_files!";
  "<C-r>" = "reset";
  "<C-l>" = "redraw_window";
  "<C-c>" = "abort";
  "<esc>" = "change_mode normal";
  "~" = "set viewmode!";
  "i" = "display_file";
  "<A-j>" = "scroll_preview 1";
  "<A-k>" = "scroll_preview -1";
  "?" = "help";
  "wW" = "display_log";
  "ww" = "taskview_open";
  "S" = "shell ";
  "W" = "console wallpaper %%s";
  ":" = "console";
  ";" = "console";
  "!" = "console shell%space";
  "@" = "console -p6 shell  %%s";
  "#" = "console shell -p%space";
  "s" = "console shell%space";
  "r" = "chain draw_possible_programs; console open_with%space";
  "f" = "console find%space";
  "cd" = "console cd%space";
  "<C-p>" = "chain console; eval fm.ui.console.history_move(-1)";
  "Mf" = "linemode filename";
  "Mi" = "linemode fileinfo";
  "Mm" = "linemode mtime";
  "Mh" = "linemode humanreadablemtime";
  "Mp" = "linemode permissions";
  "Ms" = "linemode sizemtime";
  "MH" = "linemode sizehumanreadablemtime";
  "Mt" = "linemode metatitle";
  "t" = "tag_toggle";
  "ut" = "tag_remove";
  "\"<any>" = "tag_toggle tag=%any";
  "<Space>" = "mark_files toggle=True";
  "v" = "mark_files all=True toggle=True";
  "uv" = "mark_files all=True val=False";
  "V" = "toggle_visual_mode";
  "uV" = "toggle_visual_mode reverse=True";
  "<F1>" = "help";
  "<F2>" = "rename_append";
  "<F3>" = "display_file";
  "<F4>" = "edit";
  "<F5>" = "copy";
  "<F6>" = "cut";
  "<F7>" = "console mkdir%space";
  "<F8>" = "shell trash-put %s";
  "<F10>" = "exit";
  "<UP>" = "move up=1";
  "<DOWN>" = "move down=1";
  "<LEFT>" = "move left=1";
  "<RIGHT>" = "move right=1";
  "<HOME>" = "move to=0";
  "<END>" = "move to=-1";
  "<PAGEDOWN>" = "move down=1   pages=True";
  "<PAGEUP>" = "move up=1     pages=True";
  "<CR>" = "move right=1";
  "<DELETE>" = "shell trash-put %s";
  "<INSERT>" = "console touch%space";
  "k" = "move up=1";
  "j" = "move down=1";
  "h" = "move left=1";
  "l" = "move right=1";
  "gg" = "move to=0";
  "G" = "move to=-1";
  "<C-F>" = "move down=1   pages=True";
  "<C-B>" = "move up=1     pages=True";
  "J" = "move down=0.5  pages=True";
  "K" = "move up=0.5    pages=True";
  "H" = "history_go -1";
  "L" = "history_go 1";
  "]" = "move_parent 1";
  "[" = "move_parent -1";
  "}" = "traverse";
  "{" = "traverse_backwards";
  ")" = "jump_non";
  "gh" = "cd ~";
  "ge" = "cd /etc";
  "gu" = "cd /usr";
  "gd" = "cd /dev";
  "gl" = "cd -r .";
  "gL" = "cd -r %f";
  "go" = "cd /opt";
  "gv" = "cd /var";
  "gm" = "cd /media";
  "gi" = "eval fm.cd('/run/media/' + os.getenv('USER'))";
  "gM" = "cd /mnt";
  "gs" = "cd /srv";
  "gp" = "cd /tmp";
  "gr" = "cd /";
  "gR" = "eval fm.cd(ranger.RANGERDIR)";
  "g/" = "cd /";
  "g?" = "cd /usr/share/doc/ranger";
  "E" = "edit";
  "du" = "shell -p du --max-depth=1 -h --apparent-size";
  "dU" = "shell -p du --max-depth=1 -h --apparent-size | sort -rh";
  "yp" = "yank path";
  "yd" = "yank dir";
  "yn" = "yank name";
  "y." = "yank name_without_extension";
  "=" = "chmod";
  "cw" = "console rename%space";
  "a" = "rename_append";
  "A" = ''eval fm.open_console('rename ' + fm.thisfile.relative_path.replace("%", "%%"))'';
  "I" = ''eval fm.open_console('rename ' + fm.thisfile.relative_path.replace("%", "%%"), position=7)'';
  "pp" = "paste";
  "po" = "paste overwrite=True";
  "pP" = "paste append=True";
  "pO" = "paste overwrite=True append=True";
  "pl" = "paste_symlink relative=False";
  "pL" = "paste_symlink relative=True";
  "phl" = "paste_hardlink";
  "pht" = "paste_hardlinked_subtree";
  "pd" = "console paste dest=";
  "p`<any>" = "paste dest=%any_path";
  "p'<any>" = "paste dest=%any_path";
  "pm" = "shell mpv %s &";
  "dD" = "shell trash-put %s";
  "dd" = "cut";
  "ud" = "uncut";
  "da" = "cut mode=add";
  "dr" = "cut mode=remove";
  "dt" = "cut mode=toggle";
  "yy" = "copy";
  "uy" = "uncut";
  "ya" = "copy mode=add";
  "yr" = "copy mode=remove";
  "yt" = "copy mode=toggle";
  "dgg" = "eval fm.cut(dirarg=dict(to=0), narg=quantifier)";
  "dG" = "eval fm.cut(dirarg=dict(to=-1), narg=quantifier)";
  "dj" = "eval fm.cut(dirarg=dict(down=1), narg=quantifier)";
  "dk" = "eval fm.cut(dirarg=dict(up=1), narg=quantifier)";
  "ygg" = "eval fm.copy(dirarg=dict(to=0), narg=quantifier)";
  "yG" = "eval fm.copy(dirarg=dict(to=-1), narg=quantifier)";
  "yj" = "eval fm.copy(dirarg=dict(down=1), narg=quantifier)";
  "yk" = "eval fm.copy(dirarg=dict(up=1), narg=quantifier)";
  "/" = "console search%space";
  "n" = "search_next";
  "N" = "search_next forward=False";
  "ct" = "search_next order=tag";
  "cs" = "search_next order=size";
  "ci" = "search_next order=mimetype";
  "cc" = "search_next order=ctime";
  "cm" = "search_next order=mtime";
  "ca" = "search_next order=atime";
  "<C-n>" = "tab_new";
  "<C-w>" = "tab_close";
  "<TAB>" = "tab_move 1";
  "<S-TAB>" = "tab_move -1";
  "<A-Right>" = "tab_move 1";
  "<A-Left>" = "tab_move -1";
  "gt" = "tab_move 1";
  "gT" = "tab_move -1";
  "gn" = "tab_new";
  "gc" = "tab_close";
  "uq" = "tab_restore";
  "<a-1>" = "tab_open 1";
  "<a-2>" = "tab_open 2";
  "<a-3>" = "tab_open 3";
  "<a-4>" = "tab_open 4";
  "<a-5>" = "tab_open 5";
  "<a-6>" = "tab_open 6";
  "<a-7>" = "tab_open 7";
  "<a-8>" = "tab_open 8";
  "<a-9>" = "tab_open 9";
  "<a-r>" = "tab_shift 1";
  "<a-l>" = "tab_shift -1";
  "or" = "set sort_reverse!";
  "oz" = "set sort=random";
  "os" = "chain set sort=size;      set sort_reverse=False";
  "ob" = "chain set sort=basename;  set sort_reverse=False";
  "on" = "chain set sort=natural;   set sort_reverse=False";
  "om" = "chain set sort=mtime;     set sort_reverse=False";
  "oc" = "chain set sort=ctime;     set sort_reverse=False";
  "oa" = "chain set sort=atime;     set sort_reverse=False";
  "ot" = "chain set sort=type;      set sort_reverse=False";
  "oe" = "chain set sort=extension; set sort_reverse=False";
  "oS" = "chain set sort=size;      set sort_reverse=True";
  "oB" = "chain set sort=basename;  set sort_reverse=True";
  "oN" = "chain set sort=natural;   set sort_reverse=True";
  "oM" = "chain set sort=mtime;     set sort_reverse=True";
  "oC" = "chain set sort=ctime;     set sort_reverse=True";
  "oA" = "chain set sort=atime;     set sort_reverse=True";
  "oT" = "chain set sort=type;      set sort_reverse=True";
  "oE" = "chain set sort=extension; set sort_reverse=True";
  "dc" = "get_cumulative_size";
  "zc" = "set collapse_preview!";
  "zd" = "set sort_directories_first!";
  "zh" = "set show_hidden!";
  "<C-h>" = "set show_hidden!";
  "zI" = "set flushinput!";
  "zi" = "set preview_images!";
  "zm" = "set mouse_enabled!";
  "zp" = "set preview_files!";
  "zP" = "set preview_directories!";
  "zs" = "set sort_case_insensitive!";
  "zu" = "set autoupdate_cumulative_size!";
  "zv" = "set use_preview_script!";
  "zf" = "console filter%space";
  ".d" = "filter_stack add type d";
  ".f" = "filter_stack add type f";
  ".l" = "filter_stack add type l";
  ".m" = "console filter_stack add mime%space";
  ".n" = "console filter_stack add name%space";
  ".#" = "console filter_stack add hash%space";
  ".\"" = "filter_stack add duplicate";
  ".'" = "filter_stack add unique";
  ".|" = "filter_stack add or";
  ".&" = "filter_stack add and";
  ".!" = "filter_stack add not";
  ".r" = "filter_stack rotate";
  ".c" = "filter_stack clear";
  ".*" = "filter_stack decompose";
  ".p" = "filter_stack pop";
  ".." = "filter_stack show";
  "`<any>" = "enter_bookmark %any";
  "'<any>" = "enter_bookmark %any";
  "m<any>" = "set_bookmark %any";
  "um<any>" = "unset_bookmark %any";
  "m<bg>" = "draw_bookmarks";
}
